### ISSUE TITLE
Attempting to create blog post with duplicate title / slug causes "we're sorry" error

### ISSUE THREAD

**Issue by mrueschman** [myapnea/myapnea.org#1039]
E.g. go to an existing blog post, copy title, create new blog post, paste same title, clicking create will cause error and not show some sort of uniqueness validation message

**Comment by remomueller** [comment]
I am unable to recreate this error following this: Tried it with the "obviously not" post.

<img width="1134" alt="Screen Shot 2021-04-11 at 3 31 55 PM" src="https://user-images.githubusercontent.com/316479/114318474-1c679d80-9adb-11eb-8568-dc02567a7868.png">

**Comment by mrueschman** [comment]
Ohhh - perhaps it's a bit more niche. I tried again on staging and invoked the error only when the original blog post had been deleted (but still "holds" the slug, I guess).
