### ISSUE TITLE
Allow Resources to have a PDF attachment

### ISSUE THREAD

**Issue by mrueschman** [myapnea/myapnea.org#1049]
Right now Resources have a "Link" that points to a URL. I want to 1) host a PDF on myapnea.org and 2) have the resource link point to the PDF.

Resources could have two modes:

- Link to an attached PDF
- Link to an external URL (like a YouTube video)

I would like the attached PDF to open within the browser.

**Comment by remomueller** [comment]
Addressed with fbf1ccb1a74cfa749ccc0cdbc8587ed4ee7a2d4a.
